server:
  port: 8888

#eureka:
#  instance:
#    hostname: configserver
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://discovery:8761/eureka/

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  profiles:
    active:
    - native
    
 
  cloud:
    config:
      server:
        native:
          search-locations:
          - classpath:/config