
spring:
  profiles:
    active: development
    
---
spring:
    profiles: development  
    boot:
      admin:
        client:
          url: http://localhost:9090/ 
eureka:
   instance:
     hostname: AUTHORS
   client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
       defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}   
# Ribbon config
#ribbon:
#  eureka:
#    enabled: true
---
spring:
  profiles: docker
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/  