eureka:
   client:
      registerWithEureka: false
      fetchRegistry: false
server:
   port: 8761
spring:
  boot:
    admin:
       client:
          url: http://localhost:9090/   
   
---
spring:
  profiles: docker
  cloud:
    config:
      uri: http://${DOCKER_IP:192.168.99.100}:8888   
  boot:
    admin:
      url: http://localhost:9000/    
      
