
spring:
  profiles:
    active: development
    
---
spring:
    profiles: development
eureka:
   instance:
     hostname: AUTHORS
   client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
       defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}   
# Ribbon config
#ribbon:
#  eureka:
#    enabled: true
---
spring:
  profiles: docker
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/  