
spring:
  profiles:
    active: development
    
---
spring:
    profiles: development
    application:
      name: adminserver
eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
server:
   port: 9090    
#ribbon:
#  eureka:
#    enabled: true
---
spring:
    profiles: docker
    application:
      name: adminserver
eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
